<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Score2Stream.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.12" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Commons\Commons.csproj" />
	</ItemGroup>

</Project>