<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Score2Stream.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.24.2" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\..\Commons\Commons.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\..\Training\digit_model.onnx">
			<Link>TrainedData\digit_model.onnx</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Include="..\..\Training\digit_features.onnx">
			<Link>TrainedData\digit_features.onnx</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

</Project>
