<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Score2Stream.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MessageBox.Avalonia" Version="3.3.1.1" />
		<PackageReference Include="OpenCVSharp4" Version="4.13.0.20260214" />
		<PackageReference Include="Prism.Avalonia" Version="8.1.97.11073" />
		<PackageReference Include="Xaml.Behaviors.Interactions" Version="11.3.9.5" />
		<PackageReference Include="Xaml.Behaviors.Interactivity" Version="11.3.9.5" />
	</ItemGroup>

</Project>